### ISSUE TITLE
ㅋㅋ 급식먹고싶당

### ISSUE THREAD

**Issue by Monsteel** [Seongheon03/SchoolMeal#7]
급식을 먹고싶은데 급식이 안나오는게 이슈입니다.

**Comment by ParkJin0318** [comment]
@Seongheon03 이슈 확인 부탁드립니다 :)

**Comment by ParkJin0318** [comment]
@Seongheon03 아 진짜 빨리 확인해달라고요 ;;

**Comment by Seongheon03** [comment]
@Monsteel @ParkJin0318 지금은 방학이라 급식이 없습니다 :(

**Comment by ParkJin0318** [comment]
@Seongheon03 아직 급식이 안 나오는데, reopen 부탁드립니다!
